language: python
python:
  - 3.7
  - 3.8
  - 3.9
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
install:
  - pip install ".[test]" .
script: pytest test.py
after_success:
  - codecov # submit coverage
